### PR TITLE
fixed hjkl breakage in inc/search

### PR DESCRIPTION
**Pull request by ds2606**
Fix explained in [comment](https://github.com/KoffeinFlummi/htop-vim/issues/5#issuecomment-808797334)

### CODE REVIEW

**Comment by ds2606** [comment]
similar to #8, there are some issues with the checks but having no issues with the compiled binary

The only issues with the checks were compilation with clang for ubuntu:
it seems that the checking machine uses clang-cpp 11 (which requires ubuntu >= 11.1) but runs with 11.0, doesn't seem to be an issue with the PR itself

the gcc compilation is clean as is the clang build for macos, so this looks like an issue with the checks rather than the code

**Comment by ds2606** [comment]
@KoffeinFlummi thoughts?

**Comment by KoffeinFlummi** [comment]
I'm afraid I'm not at home at the moment. I'll be able to take a look in a few days.

**Comment by ds2606** [comment]
just following up, thanks

**Comment by ds2606** [comment]
note: force push didn't change anything, it was just to re-run the tests

**Comment by KoffeinFlummi** [comment]
Thanks for the contribution!

**Pull request merged**
